---
- name: 9k test
  hosts: 9K-LEAF-B
  gather_facts: true
  connection: local

  vars:
      cli:
      username: ansible
      password: Ansible123
      transport: cli

  tasks:
    - name: create access list
      nxos_config:
        lines:
          - 10 permit ip 192.168.0.0/16 any log
          - 20 permit ip 10.0.0.0/8 any log
        parents: ip access-list ANSIBLE_TEST
        provider: "{{ cli }}"

    - name: turn on features
      nxos_config:
        lines:
          - nv overlay evpn
          - feature ospf
          - feature bgp
          - feature pim
          - feature interface-vlan
          - feature vn-segment-vlan-based
          - feature lacp
          - feature vpc
          - feature bfd
          - feature nv overlay   
        parents:
        provider: "{{ cli }}"
 
    - name: configure prod vrf
      nxos_vrf:
        vrf: PROD
        vni: 500001
        rd: auto
        username: ansible
        password: Co99erg0ld
   
    - name: configure vrf af
      nxos_vrf_af:
        vrf: PROD
        afi: ipv4
        route_target_both_auto_evpn: True
        state: present
        username: ansible   
