- name: set primary Ethernet interface
  hosts: arista
  tasks:

    - name: Setting Ethernet2 description
      eos_interface: name=Ethernet2 description=""
            username={{ eapi_username}}
            password={{ eapi_password}}
            host={{ eapi_hostname}}
            port={{ eapi_port}}
            transport=https

    - name: Ethernet2
      eos_switchport: name=Ethernet2 mode=access access_vlan=1 trunk_allowed_vlans=1-4094  
            username={{ eapi_username}}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

