---

- name: Cisco IOS testing
  hosts: cisco
  gather_facts: False

  tasks:
  - name: Testing file transfer
    cisco_file_transfer:
      source_file="/home/nbonifacio/ANSIBLE/nbonifacio_week6_logging.txt" 
      dest_file=nbonifacio_cisco_logging.txt
      overwrite=true
      enable_scp=true
      host={{ host }}
      port={{ port }}
      username={{ username }}
      password={{ password }}
